import { z } from "zod";
import { LowcoderClient } from "@aorizondo/lowcoder-agent-sdk-core";

export const GetMyOrgsInputSchema = z.object({});

/**
 * Devuelve las organizaciones a las que pertenece el usuario autenticado.
 * Útil cuando NO sabes tu `orgId` — la primera entrada es siempre la activa.
 */
export async function handleGetMyOrgs(
  client: LowcoderClient
): Promise<string> {
  const orgs = await client.listMyOrgs();
  const me = await client.getCurrentUser();

  return JSON.stringify(
    {
      userId: me.id,
      username: me.username,
      currentOrgId: me.currentOrgId,
      orgs: orgs.map((o) => ({
        orgId: o.id,
        name: o.name,
        role: o.role,
        isCurrent: o.isCurrent,
        isAutoGenerated: o.isAutoGeneratedOrganization,
      })),
      hint: `Para crear apps usa orgId: "${me.currentOrgId}" (workspace activo del usuario ${me.username})`,
    },
    null,
    2
  );
}
